name: Build Linux
on: [push]
jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Run script"
        run: |
          ./ci/build.sh
        shell: bash
        env:
          APIKEY: ${{ secrets.APIKEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: ci/bin
          retention-days: 30